import {ADD_HOUSE} from './houseTypes';
import { SEARCH_HOUSE } from './houseTypes';

export const category = {
    Residential: 1,
    Commercial: 2
}

export const propertyType = {
    Apartment: 1,
    Villa: 2,
    IndependentHouse: 3,
    Land: 4
}

export const timeFrame = {
    Monthly: 1,
    Yearly: 2
}

export const propertySizeType = {
    sqm: 1,
    acer: 2
}

export const initialState = {
    houses: [{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Damac Lagoons, Dubai',
        pincode:'12454',
        category: category.Residential,
        propertySize: '7268',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1986060.76,
        bedrooms: 7,
        bathrooms: 8,
        parking: 2,
        contactName: 'A I M Real Estate Brokers L.L.C',
        contactNumber: '+971522780383',
        contactEmail: 'AIMRealEstateBrokersL.L.C@gmail.com',
        overview: 'AIM Realty has started taking Expression of Interest for this beautiful 7-Bedroom Mansion.Enjoy Breathtaking Views Facing the Crystal Lagoons at DAMAC LAGOONS New Launch ( Portofino). There are a lot of factors to consider like the value of the property, goodwill of the developer, legal aspect, quality of house design, availability of amenities & a lot more.\n\nAmenities:\nArchitecture Style:Villa\nExterior Type:Residential floor\nLiving Room:2\nBedroom:7\nBathroo:8\nParking:covered\nProperty size:7,268 SqFt\ncategory: Residential',
        img1:'/dubai/1/image(1).png',
        img2:'/dubai/1/image(2).png',
        img3:'/dubai/1/image(3).png',
        img4:'/dubai/1/image(4).png',
        img5:'/dubai/1/image.png'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Golf City, Dubai',
        pincode:'718452',
        category: category.Residential,
        propertySize: '20000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 775911.33,
        bedrooms: 6,
        bathrooms: 7,
        parking: 5,
        contactName: 'Peace homes-JVC rentals',
        contactNumber: '+971523550929',
        contactEmail: 'Peacehomes-JVCrentals@gmail.com',
        overview: 'Paradise Hills is a vibrant community over an area of 2 million sqft located only a few minutes away from key areas in Dubai, having 170 elegantly designed villas and townhouses enriched with unique features placing them at the top of their peers in terms of quality, space, added features and value competitiveness. Located on Sheikh Zayed Bin Hamdan street; Paradise Hills is close to key locations in Dubai with its spectacular highway network connecting the city end to end in minutes.\n\nAmenties\nArchitecture Style:crafted Villa\nExterior Type:Townhouses\nLiving Room:1\nBedroom:4\nBathroo:5\nParking:3\nProperty size:3,572 SqFt\ncategory: Residential\n',
        img1:'/dubai/2/image(1).webp',
        img2:'/dubai/2/image(2).webp',
        img3:'/dubai/2/image(3).webp',
        img4:'/dubai/2/image(5).webp',
        img5:'/dubai/2/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Dubailand, Dubai',
        pincode:'605941',
        category: category.Residential,
        propertySize: '20000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 3811494.40,
        bedrooms: 6,
        bathrooms: 7,
        parking: 5,
        contactName: 'Hawk Land Properties',
        contactNumber: '+971528284908',
        contactEmail: 'HawkLandProperties@gmail.com',
        overview: 'Hawk Land Properties Offers you to live Luxury Style in The Villa Community .The Villa is a family-friendly community with several green parks, playgrounds, sports facilities, and walking/cycling paths. It also has a British school, a nursery, and 2 community centers with supermarkets, clinics, pharmacies, music schools, etc. With access to several main roads, it is within 20-25 minutes from central places like Downtown and the Burj Khalifa, Dubai International Airport, and the beach.\n\nArchitecture Style:Villa\nExterior Type:Crema finish flooring\nLiving Room:2\nBedroom:6\nBathroo:7\nParking:5\nProperty size:20,000 SqFt\ncategory: Residential',
        img1:'/dubai/3/image(1).webp',
        img2:'/dubai/3/image(2).webp',
        img3:'/dubai/3/image(3).webp',
        img4:'/dubai/3/image(4).webp',
        img5:'/dubai/3/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Legacy Small, Legacy',
        pincode:'605941',
        category: category.Residential,
        propertySize: '5650',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1116223.36,
        bedrooms: 3,
        bathrooms: 4,
        parking: 2,
        contactName: 'HawkLandProperties',
        contactNumber: '+971524748759',
        contactEmail: 'HawkLandProperties@gmail.com',
        overview: 'Located at the heart of Dubai`s most desirable residential district, Jumeirah Park is a secure, family-orientated residential community spread over 350 hectares. The community contains 2,000 stylish, luxury family villas, surrounded by expansive, verdant, eco-friendly parks and green spaces, as well as a host of integrated amenities\n\nArchitecture Style:Villa\nExterior Type: back yard..\nLiving Room:1 Main\nBedroom:3\nBathroom:4\nParking:2\nProperty size:5,650 SqFt\ncategory: Residential',
        img1:'/dubai/4/image(1).webp',
        img2:'/dubai/4/image(2).webp',
        img3:'/dubai/4/image(3).webp',
        img4:'/dubai/4/image(5).webp',
        img5:'/dubai/4/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Cedre Villas, Dubai Silicon Oasis',
        pincode:'702719',
        category: category.Residential,
        propertySize: '3900',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 830361.28,
        bedrooms: 3,
        bathrooms: 4,
        parking: 2,
        contactName: 'Pyramid star',
        contactNumber: '0559996151',
        contactEmail: 'pyramidstar@gmail.com',
        overview: 'Cadre Villas, a part of Silicon Oasis is a free zone community (with1207 Residential Units) that started in 2005 and was completed in 2009. This Community comprises 3, 4 & 5 Bedroom Villas (3,700 sq. ft to 7280 sq. ft) plus all necessary amenities of a luxury society. It is located near Sheik M.Bin Zayed Road (E311) with 10 minutes distance from Academic City.\n\nArchitecture Style:Cedre Villas,\nExterior Type:Dubai Silicon Oasis.\nLiving Room:1 Main\nBedroom:3\nBathroo:4\nParking:2\nProperty size:3,900 SqFt\ncategory: Residential',
        img1:'/dubai/5/image(1).webp',
        img2:'/dubai/5/image(2).webp',
        img3:'/dubai/5/image(3).webp',
        img4:'/dubai/5/image(4).webp',
        img5:'/dubai/5/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Al Furjan, Dubai',
        pincode:'606477',
        category: category.Residential,
        propertySize: '5447',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1225123.20,
        bedrooms: 4,
        bathrooms: 4,
        parking: 2,
        contactName: 'Aeon and Trisl',
        contactNumber: '+971524195364',
        contactEmail: 'AeonandTrisl@gmail.com',
        overview: '5 Mins away from IBN Batuta Mall.Near to Al Furjan Pavilion.Metro Linked Community.The Quortaj Style villas combine an eclectic mix of colours and textures that showcase attention to detail Tiered, green tile roofs and embellished white panels accentuated by unique design. Dubai Style one of Nakheel`s most popular and fastest growing communities, easy access to the rest of the city.\n\nArchitecture Style:Quortaj Style villa\nExterior Type:green tile roofs\nLiving Room:1\nBedroom:4\nBathroo:4\nParking:2\nProperty size:5,447 SqFt\ncategory: Residential',
        img1:'/dubai/6/image(1).webp',
        img2:'/dubai/6/image(2).webp',
        img3:'/dubai/6/image(3).webp',
        img4:'/dubai/6/image(5).webp',
        img5:'/dubai/6/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Murooj Al Furjan, Al Furjan',
        pincode:'606477',
        category: category.Residential,
        propertySize: '2586',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 587732.44,
        bedrooms: 4,
        bathrooms: 5,
        parking: 3,
        contactName: 'Muhammad Gul Sher',
        contactNumber: '+971524195364',
        contactEmail: 'aeonandtrisl@gmail.com',
        overview: 'Aeon & Trisl proudly offers you a 4 Bedroom Townhouse in a luxurious new community by Nakheel, named Al Furjan, with elegant homes, perfectly located in the well-established Al Furjan master development.\nAl Furjan is a residential area near Jebel Ali that is ideal for families of all sizes. It consists of four villages, and includes 4000 houses, apartments, hotels, as well as commercial and mixed use plots in an area of 5.6 million sq. meters\n\nArchitecture Style:Townhouses and villa\nExterior Type:Ground floor\nLiving Room:1\nBedroom:4\nBathroo:5\nParking:3\nProperty size:2,586 SqFt\ncategory: Residential',
        img1:'/dubai/7/image(1).webp',
        img2:'/dubai/7/image(2).webp',
        img3:'/dubai/7/image(3).webp',
        img4:'/dubai/7/image(4).webp',
        img5:'/dubai/7/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'JVT District 9, Jumeirah Village Triangle (JVT)',
        pincode:'904341',
        category: category.Residential,
        propertySize: '6994',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 816748.80,
        bedrooms: 2,
        bathrooms: 3,
        parking: 2,
        contactName: 'THE BEST KEY REAL ESTATE',
        contactNumber: '971522047485',
        contactEmail: 'THEBESTKEYREALESTATE@gmail.com',
        overview: 'To Sellers / Landlords: Dont miss out on our READY Buyers and Tenants in Palm Jumeirah, Jumeirah Park, JBR, Dubai Marina,JLT, Emirates Living and Downtown Burj Areas.\nThe Best Key Real Estate Services Offered: -Residential Sales and Lettings - Commercial Sales and Lettings - Property Management Services - Mortgage Services - Buildings - Hotels\n\nArchitecture Style:Villa\nExterior Type: Village Triangle \nLiving Room:1\nBedroom:2\nBathroo:3\nParking:2\nProperty size:6,994 SqFt\ncategory: Residentia',
        img1:'/dubai/8/image(1).webp',
        img2:'/dubai/8/image(2).webp',
        img3:'/dubai/8/image(3).webp',
        img4:'/dubai/8/image(5).webp',
        img5:'/dubai/8/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'DUBAI HILLS ESTATE',
        pincode:'768954',
        category: category.Residential,
        propertySize: '180,000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 816748.800,
        bedrooms: 8,
        bathrooms: 7,
        parking: 4,
        contactName: 'DUBAI HILLS ESTATE',
        contactNumber: '+97154675498',
        contactEmail: 'DUBAIHILLSESTATE@gmail.comcom',
        overview: 'Wake up to luscious landscaped greens and pristine fairways with an iconic backdrop of the Burj Khalifa and the Dubai skyline. Live in a sophisticated address that inspires peak performance, every day. Come home to the Dubai Hills Estate.\n\nProperty features:\nArchitecture Style:Villa\nExterior Type:Green square\nLiving Room:2\nBedroom:8\nBathroo:7\nParking:4\nProperty size:180,000 sqm\ncategory: Residential',
        img1:'/dubai/9/image(1).jpg',
        img2:'/dubai/9/image(2).jpeg',
        img3:'/dubai/9/image(3).jpg',
        img4:'/dubai/9/image(4).jpg',
        img5:'/dubai/9/image.jpg'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Hessa St. & Sheikh Hamdan Bin Nahyan St.',
        pincode:'695029',
        category: category.Residential,
        propertySize: '2944',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 587786.89,
        bedrooms: 5,
        bathrooms: 6,
        parking: 2,
        contactName: 'AIM real estate',
        contactNumber: '+917522780383',
        contactEmail: 'AIMrealestatebrokers@gmail.com',
        overview: 'Connecting cities with water and activity hubs.Regional Mall ( Tentatively upto 2 Million sq.ft - almost bigger than MOE ).Retail Units sitting inside the Island connecting by the bridge -.Water Integrated Amphitheater\nCrystal Lagoon Experience\nFirst Water cinema ( Floating Cinema ).Created Natural Mountains with caves with Water falls giving you access to the F and B areas.F&B with Bars Island in the middle of the community.\n\nArchitecture Style:Luxury Villa\nExterior Type:Resort Living\nLiving Room:1\nBedroom:5\nBathroo:6\nParking:2\nProperty size:2,944 SqFt\ncategory: Residential',
        img1:'/dubai/10/image(1).webp',
        img2:'/dubai/10/image(2).webp',
        img3:'/dubai/10/image(3).webp',
        img4:'/dubai/10/image(4).webp',
        img5:'/dubai/10/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Mirdif 44 Villas, Mirdif',
        pincode:'563031',
        category: category.Residential,
        propertySize: '10,000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1279573.12,
        bedrooms: 5,
        bathrooms: 7,
        parking: 2,
        contactName: 'Unesco real estate',
        contactNumber: '+971556950475',
        contactEmail: 'unescorealestate@gmail.com',
        overview: 'For sale a two-storey villa in Mirdif, consisting of 5 master bedrooms, a hall, a Majlis, external annexes and a planted garden far from the flight line, a very special location\n\nArchitecture Style:villa in Mirdi\nExterior Type:planted garden\nLiving Room:1\nBedroom:5\nBathroo:7\nParking:2\nProperty size:10,000 SqFt\ncategory: Residential',
        img1:'/dubai/11/image(1).webp',
        img2:'/dubai/11/image(2).webp',
        img3:'/dubai/11/image(3).webp',
        img4:'/dubai/11/image(4).webp',
        img5:'/dubai/11/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Amaranta 1, Amaranta',
        pincode:'695029',
        category: category.Residential,
        propertySize: '2314',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 537442.76,
        bedrooms: 4,
        bathrooms: 5,
        parking: 1,
        contactName: 'AIM real estate broker',
        contactNumber: '+971523620520',
        contactEmail: 'AIMrealestatebroker@gmail.com',
        overview: 'Amaranta by Villanova is located near the intersection of Emirates Road and Al Ain Road along Emirates Road.Lively and vibrant gated community surrounded by lush greenery.Part of 2.153 million sq. m community with a developed retail area.\n\nArchitecture Style:Maids Villa_\nExterior Type:Townhouses\nLiving Room:1\nBedroom:4\nBathroo:5\nParking:1\nProperty size:2,314 SqFt\ncategory: Residential',
        img1:'/dubai/12/image(1).webp',
        img2:'/dubai/12/image(2).webp',
        img3:'/dubai/12/image(3).webp',
        img4:'/dubai/12/image(5).webp',
        img5:'/dubai/12/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Lagoons, Dubai',
        pincode:'695029',
        category: category.Residential,
        propertySize: '3248',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 696686.73,
        bedrooms: 5,
        bathrooms: 5,
        parking: 2,
        contactName: 'AIM real estate broker',
        contactNumber: '+971522780383',
        contactEmail: 'AIMrealestatebroker@gmail.com',
        overview: 'AIM Properties proudly presents you this beautiful 5 bedroom townhouse in Damac Lagoons.ituated on main Hessa street, Damac Lagoons offers fantastic accessibility to all the major highways and offers its residents a holiday living throughout.\n\nArchitecture Style:Spanish Style\nExterior Type:Luxurious 5BR Villa\nLiving Room:1 Main\nBedroom:5\nBathroo:5\nParking:2\nProperty size:3,248 SqFt\ncategory: Residential',
        img1:'/dubai/13/image(1).webp',
        img2:'/dubai/13/image(2).webp',
        img3:'/dubai/13/image(3).webp',
        img4:'/dubai/13/image(4).webp',
        img5:'/dubai/13/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Damac Lagoons, Dubai',
        pincode:'695029',
        category: category.Residential,
        propertySize: '2944',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 615011.85,
        bedrooms: 6,
        bathrooms: 5,
        parking: 2,
        contactName: 'L.L.C brokers',
        contactNumber: '+917522780383',
        contactEmail: 'L.L.Cbrokers@gmail.com',
        overview: 'Lavish 4BR Villa | French Style | Classic ViewsNICE French Style Villas Nice at DAMAC Lagoons opens your world to villas surrounded by classic French feels, with escapes for the young, and the young at heart.The French-style homes at Nice capture the charm of the quintessential French city with inspiring architecture, vivid hues and thoughtfully designed spaces.\n\nArchitecture Style:French Style \nExterior Type:Lavish 4BR Villa \nLiving Room:1\nBedroom:6\nBathroo:5\nParking:2\nProperty size:2,944 SqFt\ncategory: Residential',
        img1:'/dubai/14/image(1).webp',
        img2:'/dubai/14/image(2).webp',
        img3:'/dubai/14/image(3).webp',
        img4:'/dubai/14/image(5).webp',
        img5:'/dubai/14/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Damac Lagoons, Dubai',
        pincode:'695029',
        category: category.Residential,
        propertySize: '2944',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 585336.64,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'L.L.C brokers',
        contactNumber: '+917522780383',
        contactEmail: 'LLCbrokers@gmail.com',
        overview: '4BR & 5BR Townhouses surrounded by Lagoon Selling Price starts from Aed 1.6 Mil.45 million square feet community Urban & Mediterranean Design.Villas & Townhouses integrated with the lagoon Crystal Blue Lagoon.\n\nArchitecture Style:SPACIOUS 5BR VILLA\nExterior Type:Urban & Mediterranean Design\nLiving Room:1\nBedroom:5\nBathroo:5\nParking:3\nProperty size:2,944 SqFt\ncategory: Residential',
        img1:'/dubai/15/image(1).webp',
        img2:'/dubai/15/image(2).webp',
        img3:'/dubai/15/image(3).webp',
        img4:'/dubai/15/image(4).webp',
        img5:'/dubai/15/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Damac Lagoons, Dubai',
        pincode:'695029',
        category: category.Residential,
        propertySize: '2944',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 569001.66,
        bedrooms: 5,
        bathrooms: 5,
        parking: 2,
        contactName: 'Syed',
        contactNumber: '+971523629762',
        contactEmail: 'SyedAgent@gmail.com',
        overview: 'AIM Properties has been recognized as a leader in the market of distinctive and luxury properties, committed to high performance and professionalism. With our lucrative and auspicious background of finance & investment, we deliver excellence in real estate. We promise a swift response, the highest standard of service.\n\nArchitecture Style:TOWNHOUSE \nExterior Type:3BR w. Maid\nLiving Room:1\nBedroom:5\nBathroo:5\nParking:2\nProperty size:2,944 SqFt\ncategory: Residential',
        img1:'/dubai/16/image(1).webp',
        img2:'/dubai/16/image(2).webp',
        img3:'/dubai/16/image(3).webp',
        img4:'/dubai/16/image(5).webp',
        img5:'/dubai/16/image.webp'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Abu Dhabi Emirate',
        location:'Expo 2020 Dubai– 8 min',
        pincode:'2922-Ap-S-0018',
        category: category.Residential,
        propertySize: '732',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 155936.40,
        bedrooms: 1,
        bathrooms: 1,
        parking: 1,
        contactName: 'Aldar',
        contactNumber: '+971509036700',
        contactEmail: 'Aldarproperties@gmail.com',
        overview: 'In Abu Dhabi but located close to the border of Dubai and minutes from Expo 2020 Dubai, Al ghadeer is a sustainable community that embraces nature and the best of two cities. With 2,100 maisonettes, townhouses and villas already built and occupied, another 14,000 are set to be handed over in April 2021.\n\nArchitecture Style:Apartment\nExterior Type:Maisonette\nLiving Room:1\nBedroom:1\nBathroo:1\nParking:1\nProperty size:732 sqft\ncategory: Residential',
        img1:'/dubai/17/image(1).jfif',
        img2:'/dubai/17/image(2).jfif',
        img3:'/dubai/17/image(3).jfif',
        img4:'/dubai/17/image(4).jfif',
        img5:'/dubai/17/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Al Ghadeer Phase II, Al Ghadeer, Abu Dhabi',
        pincode:'2922-Ap-S-0024',
        category: category.Residential,
        propertySize: '1058',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 198116.03,
        bedrooms: 2,
        bathrooms: 2,
        parking: 1,
        contactName: 'Aldar',
        contactNumber: '+971566789043',
        contactEmail: 'Aldarproperties@gmail.com',
        overview: 'Aldar Properties PJSC is the leading real estate developer in Abu Dhabi, and through its iconic developments, it is one of the most well known in the United Arab Emirates, and wider Middle East region.\n\nArchitecture Style:Apartment\nExterior Type:Maisonette\nLiving Room:1\nBedroom:2\nBathroo:2\nParking:1\nProperty size:1,058 sqft\ncategory: Residential',
        img1:'/dubai/18/image(1).jfif',
        img2:'/dubai/18/image(2).jfif',
        img3:'/dubai/18/image(3).jfif',
        img4:'/dubai/18/image(4).jfif',
        img5:'/dubai/18/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Al Ghadeer Phase II, Al Ghadeer, Abu Dhabi',
        pincode:'2922-Ap-S-0025',
        category: category.Residential,
        propertySize: '662',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 148449.54,
        bedrooms: 1,
        bathrooms: 1,
        parking: 1,
        contactName: 'Adlar',
        contactNumber: '+97134765987',
        contactEmail: 'Adlarproperties@gmail.com',
        overview: 'From its beginnings in 2005 through to today, Aldar continues to shape and enhance the urban fabric of the UAE’s capital city in addition to other key areas of the emirate.\n\nArchitecture Style:Apartment\nExterior Type:Amazing 1Bedroom Maisonette\nLiving Room:1\nBedroom:1\nBathroo:1\nParking:1\nProperty size:662 sqft\ncategory: Residential',
        img1:'/dubai/19/image(1).jfif',
        img2:'/dubai/19/image(2).jfif',
        img3:'/dubai/19/image(3).jfif',
        img4:'/dubai/19/image(4).jfif',
        img5:'/dubai/19/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Ajmal Makan, Sharjah Waterfront City, Sharjah',
        pincode:'7849-ol6C1d',
        category: category.Residential,
        propertySize: '2774',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 735073.92,
        bedrooms: 4,
        bathrooms: 5,
        parking: 2,
        contactName: 'Hasan Zainab',
        contactNumber: '+97156698445',
        contactEmail: 'Truehomes@gmail.com',
        overview: 'Sea villas in the Ajmal Makan project in Sharjah.Own and invest in the largest project on the sea in Sharjah.Villas are 3 floors with modern, luxurious and smart designs, with stunning sea views, distributed over 10 islands on the Hamiriya Sea, Sharjah.\n\nArchitecture Style:villa\nExterior Type:luxurious and smart designs\nLiving Room:1 Main\nBedroom:4\nBathroo:5\nParking:2\nProperty size:2,774 sqft\ncategory: Residential',
        img1:'/dubai/20/image(1).jfif',
        img2:'/dubai/20/image(2).jfif',
        img3:'/dubai/20/image(3).jfif',
        img4:'/dubai/20/image(4).jfif',
        img5:'/dubai/20/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Sharjah Waterfront City, Sharjah',
        pincode:'7849-ArUzBU',
        category: category.Residential,
        propertySize: '2774',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 735073.92,
        bedrooms: 4,
        bathrooms: 5,
        parking: 2,
        contactName: 'Fahda Tahtah',
        contactNumber: '+9716784376',
        contactEmail: 'Truehomes@gmail.com',
        overview: 'Sharjah Waterfront City has been carefully designed to ensure the highest levels of comfort for families, offering them an atmosphere of privacy while enjoying a stunning beach view. The views outside the villas and apartments are a mixture of open beaches and lush greenery to form a breathtaking beauty with its splendor.\n\nrchitecture Style:Villa\nExterior Type:Luxrious villa\nLiving Room:1\nBedroom:4\nBathroo:5\nParking:2\nProperty size:2,774 sqft\ncategory: Residential',
        img1:'/dubai/21/image(1).jfif',
        img2:'/dubai/21/image(2).jfif',
        img3:'/dubai/21/image(3).jfif',
        img4:'/dubai/21/image(4).jfif',
        img5:'/dubai/21/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'The St. Regis Residences, Downtown Dubai, Dubai',
        pincode:'768954',
        category: category.Residential,
        propertySize: '1161',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 881513.71,
        bedrooms: 2,
        bathrooms: 3,
        parking: 1,
        contactName: 'Hannan khan',
        contactNumber: '+97135876523',
        contactEmail: 'azcorealestate@gmail.com',
        overview: 'St. Regis Residences is a meticulously planned luxurious resident building that offers a lifestyle best suited for people who cherish the highest standard of luxury living. Start living in one of the most prestigious addresses in the region with ultra-luxurious apartments located alongside the world-famous Burj Khalifa and Dubai Fountain.\n\nArchitecture Style:Villa\nExterior Type:French style\nLiving Room:1\nBedroom:2\nBathroom:3\nParking:1\nProperty size:1,161 sqft\ncategory: Residential',
        img1:'/dubai/22/image(1).jfif',
        img2:'/dubai/22/image(2).jfif',
        img3:'/dubai/22/image(3).jfif',
        img4:'/dubai/22/image(4).jfif',
        img5:'/dubai/22/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'The St. Regis Residences',
        pincode:'765908',
        category: category.Residential,
        propertySize: '1181',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 881753.71,
        bedrooms: 3,
        bathrooms: 3,
        parking: 1,
        contactName: 'Hannan khan',
        contactNumber: '+97145698325',
        contactEmail: 'azcorealestate@gmail.com',
        overview: 'The Downtown District is well connected to the city’s other major economic and residential sectors. Sheikh Zayed Road, E11, is strategically placed across Al Wasl and inside Business Bay, in a residential region close to home and life.\n\nArchitecture Style:VillaExterior Type:French styleLiving Room:1Bedroom:3Bathroo:3Parking:1Property size:1,181 sqftcategory: Residential',
        img1:'/dubai/23/image(1).jfif',
        img2:'/dubai/23/image(2).jfif',
        img3:'/dubai/23/image(3).jfif',
        img4:'/dubai/23/image(4).jfif',
        img5:'/dubai/23/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Oceana Aegean',
        pincode:'12328',
        category: category.Residential,
        propertySize: '2439',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1497372.80,
        bedrooms: 3,
        bathrooms: 4,
        parking: 2,
        contactName: 'Rayn James paul Coleman',
        contactNumber: '+97167845907',
        contactEmail: 'luxuryproperty@gmail.com',
        overview: 'LuxuryProperty. com would like to offer this three-bedroom apartment for sale located in the high-end Oceana Residences on the Palm Jumeirah.\n\nArchitecture Style:Apartment\nExterior Type: Palm Jumeirah\nLiving Room:1\nBedroom:3\nBathroo:4\nParking:2\nProperty size:2,439 sqft\ncategory: Residential',
        img1:'/dubai/24/image(1).jfif',
        img2:'/dubai/24/image(2).jfif',
        img3:'/dubai/24/image(3).jfif',
        img4:'/dubai/24/image(4).jfif',
        img5:'/dubai/24/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Arab Emirates', isoCode: 'AE', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Dubai',
        location:'Oceana, Palm Jumeirah, Dubai',
        pincode:'65789',
        category: category.Residential,
        propertySize: '2639',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1897372.80,
        bedrooms: 5,
        bathrooms: 4,
        parking: 2,
        contactName: 'Rayn james paul coleman',
        contactNumber: '+97198560984',
        contactEmail: 'Luxuryproperty@gmail.com',
        overview: 'Oceana is a beachfront resort community centrally located on the Palm Jumeirah. It is a dynamic residential and resort community that offers private beach access and panoramic views of the Dubai Marina skyline. Furthermore, there is the newly opened Ula restaurant which is run by the STK, Koyo and Asia Asia team providing a superb fine dining experience.\n\nArchitecture Style:Villa\nExterior Type:French style\nLiving Room:1\nBedroom:5\nBathroo:4\nParking:2\nProperty size:2,639 sqft\ncategory: Residential',
        img1:'/dubai/25/image(1).jfif',
        img2:'/dubai/25/image(2).jfif',
        img3:'/dubai/25/image(3).jfif',
        img4:'/dubai/25/image(4).jfif',
        img5:'/dubai/25/image.jfif'
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Newyork',
        location:'Arlington Heights',
        pincode:'60005',
        category: category.Residential,
        propertySize: '5000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1100000,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'Maria DelBoccio',
        contactNumber: '847.495.2510',
        contactEmail: 'Mariadelbaccio@gmail.com',
        overview: 'Here is your opportunity to own a true "one of a kind" home! Situated on a double lot, this estate like residence is truly remarkable. Dramatic yet inviting floor plan offers: sensational kitchen appointed with only the highest caliber of materials.Positioned in a prime location: minutes to absolutely everything.\n\nArchitecture Style: Colonial \nExterior Type: Brick,Cedar,Stone\nLiving Room:22x22 - Main \nBedroom:5\nBathroom:5\nParking:3\nProperty size:  5,000 Sqft\ncategory:Residential ',
        img1:'/usa/1/1.jpg',
        img2:'/usa/1/2.jpg',
        img3:'/usa/1/3.jpg',
        img4:'/usa/1/4.jpg',
        img5:'/usa/1/5.jpg',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Illinois',
        location:'Chicago, 1425 N State Parkway',
        pincode:'60610',
        category: category.Residential,
        propertySize: '8257',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 5250000,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'Kirste Gaudet',
        contactNumber: '773.330.6956',
        contactEmail: 'Kirstegaudet@gmail.com',
        overview: 'Grand and elegant home in the heart of the Gold Coast on a wide and deep lot. Extraordinary --approximately 8000 square foot --floorplan. Beautifully updated and maintained. The house has huge gracious formal entertaining rooms and wonderful casual/comfortable rooms for day-to-day living. Gorgeous facade. Property has been impeccably cared for. Steps to all the Gold Coast offers.\n\nArchitecture Style:Georgian\nExterior Type:Brick,Stone\nLiving Room: 13x39 - Main\nBedroom:7\nBathroom:7\nParking:2\nProperty size:8257 Sqft  \ncategory: Residential',
        img1:'/usa/2/1.jpg',
        img2:'/usa/2/2.jpg',
        img3:'/usa/2/3.jpg',
        img4:'/usa/2/4.jpg',
        img5:'/usa/2/5.jpg',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Massachusetts',
        location:'Boston, 48 Cook St #1',
        pincode:'MA 02129',
        category: category.Residential,
        propertySize: '1608',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 979000,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'Laura T',
        contactNumber: '72948951',
        contactEmail: 'lauraT@gmail.com',
        overview: 'Custom 2019 new construction that won`t disappoint in the heart of Charlestown. This home has the perfect layout for entertaining as the living and dining areas open up to a chef`s kitchen consisting of a large island made of Statuary Classique Quartz countertops with waterfall edge, SS appliances, custom cabinetry, gas cooking and a breakfast bar. This quiet street is a short walk to Charlestown`s restaurants, shops, the T, the bus and Whole Foods.\n\nArchitecture Style:Attached,Condo\nExterior Type:Patio / Porch: Deck\nLiving Room:1\nBedroom:3\nBathroom:2\nParking:1\nProperty size:1,608 sqft  \ncategory: Residential',
        img1:'/usa/3/1.webp',
        img2:'/usa/3/2.webp',
        img3:'/usa/3/3.webp',
        img4:'/usa/3/4.webp',
        img5:'/usa/3/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Massachusetts',
        location:'Charlestown,1 Wistar Pl #1',
        pincode:'MA 02129',
        category: category.Residential,
        propertySize: '1058',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 699900,
        bedrooms: 1,
        bathrooms: 2,
        parking: 1,
        contactName: 'LAER Realty Partners',
        contactNumber: '72953218',
        contactEmail: 'LAERRealtyPartners@gmail.com',
        overview: 'Don`t miss this 1+/2-bedroom, 2-bathroom, townhouse, with a deeded parking space, on a private way in Charlestown. Walking up the granite steps, you`ll enter the private entrance into the open concept living/dining/kitchen area. This pet-friendly property has exclusive roof rights to build a private roof deck.\n\nArchitecture Style:Townhouse,Condo\nExterior Type:Patio / Porch: Deck - Roof + Access Rights, Covered\nLiving Room:1\nBedroom:1\nBathroom:2\nParking:1\nProperty size: 1,058 sqft \ncategory: Residential',
        img1:'/usa/4/1.webp',
        img2:'/usa/4/2.webp',
        img3:'/usa/4/3.webp',
        img4:'/usa/4/4.webp',
        img5:'/usa/4/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United Kingdom', isoCode: 'GB', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'London Borough of Barking and Dagenham',
        location:'1 Front St, Chelsea',
        pincode:'MA 02150',
        category: category.Residential,
        propertySize: '1368',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 549900,
        bedrooms: 3,
        bathrooms: 3,
        parking: 1,
        contactName: 'M.Celata Real Estate',
        contactNumber: '72949703',
        contactEmail: 'M.CelataRealEstate@gmail.com',
        overview: 'This home is located conveniently near Rt. 1 which you can take to 93, Minutes from BEAN TOWN. This home has many renovated updates and is in move condition.Newer roof, new er heater, updated newer windows. 3 beds and 2.5 baths including a master with walk in closet and LAUNDRY right insider the property on the 2nd floor. renovated Kitchen displays Granite counter Tops and Stainless steel appliance!!!\n\nArchitecture Style: Colonial\nExterior Type:Asphalt Fiberglass Shingles\nLiving Room:1\nBedroom:3\nBathroom:3\nParking:1\nProperty size:1,368 sqft\ncategory: commercial',
        img1:'/usa/5/1.webp',
        img2:'/usa/5/2.webp',
        img3:'/usa/5/3.webp',
        img4:'/usa/5/4.webp',
        img5:'/usa/5/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'North Scottsdale, 8101 E Cortez Dr',
        pincode:'AZ 85260',
        category: category.Commercial,
        propertySize: '2371',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 999999,
        bedrooms: 4,
        bathrooms: 3,
        parking: 2,
        contactName: 'MUNRO REALTY INTERNATIONAL',
        contactNumber: '6368051',
        contactEmail: 'MUNROREALTYINTERNATIONAL@gmail.com',
        overview: 'Perfect house situated on Starfire Golf Club in Scottsdale Country Club Development, with views of McDowell Mountains. Since purchased, Homeowner has updated numerous rooms to offer an up to date, move in ready experience. Open kitchen, has upgraded Granite Countertops with stainless steel appliances.\n\nArchitecture Style:Contemporary\nExterior Type:Private Yard\nLiving Room:1\nBedroom:4\nBathroo:3\nParking:Garage 2 space\nProperty size:2,371 sqft\ncategory: commercial',
        img1:'/usa/6/1.webp',
        img2:'/usa/6/2.webp',
        img3:'/usa/6/3.webp',
        img4:'/usa/6/4.webp',
        img5:'/usa/6/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'North Scottsdale, 295XX N 166th St',
        pincode:'AZ 85262',
        category: category.Residential,
        propertySize: '1575',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 498900,
        bedrooms: 3,
        bathrooms: 2,
        parking: 1,
        contactName: 'Morgan Taylor Realty',
        contactNumber: '6226048',
        contactEmail: 'MorganTaylorRealty@gmail.com',
        overview: 'TO BE BUILT HOME *** Amazing open floor concept with a split floor plan. The Great Room adjoins the Kitchen, which features White Shaker Style Cabinets with Soft Close Drawers and Doors, Granite Countertops, Stainless Steel Appliances, with Wood-like Tile throughout all the main areas. The Master Suite offers a sizeable Walk-in Closet, with Dual Executive Height Sinks, and an Oversized Shower.\n\nArchitecture Style:Cholla\nExterior Type:Roof: Tile\nLiving Room:1\nBedroom:3\nBathroo:2\nParking:1\nProperty size:1,575 sqft (on 1.10 acres)\ncategory: Residential',
        img1:'/usa/7/1.webp',
        img2:'/usa/7/2.webp',
        img3:'/usa/7/3.webp',
        img4:'/usa/7/4.webp',
        img5:'/usa/7/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'16439 E Desert Vista Trl',
        pincode:'AZ 85262',
        category: category.Residential,
        propertySize: '2191',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 640000,
        bedrooms: 3,
        bathrooms: 3,
        parking: 1,
        contactName: 'North Scottsdale Land Development, Inc',
        contactNumber: '6340865',
        contactEmail: 'NorthScottsdaleLandDevelopmentInc@gmail.com',
        overview: 'This is one of the only houses in Rio Verde for under $295 a square foot. Imagine waking up to the sunrise over Four Peaks Mountain. This beautiful home sits on just over an acre of property, which offers plenty of privacy. The home features high-end finishes throughout with a fenced-in backyard.\n\nArchitecture Style:Single Family Residence\nExterior Type:Roof: Comp Shingle,Fencing: Wrought Iron\nLiving Room:1\nBedroom:3\nBathroo:3\nParking:1\nProperty size:2,191 sqft\nategory: Residential',
        img1:'/usa/8/1.webp',
        img2:'/usa/8/2.webp',
        img3:'/usa/8/3.webp',
        img4:'/usa/8/4.webp',
        img5:'/usa/8/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'29424 N 138th St',
        pincode:'AZ 85262',
        category: category.Commercial,
        propertySize: '3800',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1550000,
        bedrooms: 4,
        bathrooms: 3,
        parking: 3,
        contactName: 'Launch Real Estate',
        contactNumber: '6364586',
        contactEmail: 'LaunchRealEstate@gmail.com',
        overview: 'Customized one-story home on 1.25 acres with incredible mountain views in every direction, stunning views of 4 Peaks. Upgrades throughout: gourmet kitchen opens to great room w/stacked stone FP and custom brick walls. Windows maximize the views, new 4 pane, telescoping doors in great room. Huge master suite with access to custom pool/spa with water feature and leather top entertainment bar.\n\nArchitecture Style: Territorial/Santa Fe\nExterior Type: Private Yard\nLiving Room:1\nBedroom:4\nBathroo:3\nParking:3\nProperty size:3,800 sqft (on 1.24 acres)\ncategory: commercial',
        img1:'/usa/9/1.webp',
        img2:'/usa/9/2.webp',
        img3:'/usa/9/3.webp',
        img4:'/usa/9/4.webp',
        img5:'/usa/9/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'6924 E Avalon Dr',
        pincode:'AZ 85251',
        category: category.Residential,
        propertySize: '1309',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 625000,
        bedrooms: 3,
        bathrooms: 2,
        parking: 1,
        contactName: 'HomeSmart',
        contactNumber: 'MLS#6370329',
        contactEmail: 'HomeSmart@gmail.com',
        overview: 'This home has been lovingly cared for by the original owner since 1957! Come make it your own! The location is PRIME. The home is located within walking distance to Old Town Scottsdale, countless restaurants, shopping, nightlife, spring training facilities, hiking, and the airport is just minutes away. You can`t ask for a better location!\n\nArchitecture Style: Ranch\nExterior Type:Patio / Porch: Covered Patio(s), Patio\nLiving Room:1 Main\nBedroom:3\nBathroo:2\nParking:1\nProperty size:1,309 sqft\ncategory: Residential',
        img1:'/usa/10/1.webp',
        img2:'/usa/10/2.webp',
        img3:'/usa/10/3.webp',
        img4:'/usa/10/4.webp',
        img5:'/usa/10/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Arizona',
        location:'10931 E Lillian Ln',
        pincode:'AZ 85255',
        category: category.Residential,
        propertySize: '2958',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1400000,
        bedrooms: 4,
        bathrooms: 4,
        parking: 3,
        contactName: 'Platinum Living Realty',
        contactNumber: 'MLS#6369437',
        contactEmail: 'PlatinumLivingRealty@gmail.com',
        overview: 'Find true luxury in the sought-after, gated neighborhood of Trovas. This Scottsdale oasis offers the best that McDowell Mountain Ranch has to offer. It is situated in the Easternmost section of the community and borders the Sonoran Preserve, making for magnificent views you can`t find anywhere else.\n\nArchitecture Style: Contemporary\nExterior Type:Trovas\nLiving Room:1\nBedroom:4\nBathroo:4\nParking:3\nProperty size:2,958 sqft (on 0.27 acres)\ncategory:  Residential',
        img1:'/usa/11/1.webp',
        img2:'/usa/11/2.webp',
        img3:'/usa/11/3.webp',
        img4:'/usa/11/4.webp',
        img5:'/usa/11/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'3718 Hillview St',
        pincode:'CA 94602',
        category: category.Residential,
        propertySize: '984',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 799000,
        bedrooms: 2,
        bathrooms: 2,
        parking: 1,
        contactName: 'Mark Hardwicke',
        contactNumber: 'MLS#40985433',
        contactEmail: 'MarkHardwicke@gmail.com',
        overview: 'Nestled on a quiet cul-de-sac in the desirable Upper Dimond district, this refreshed, appealing bungalow offers delightful surprises, including additional flex space. Freshly painted, there are many smart design updates, such as modern lighting, appliances, and refinished hardwood floors.\n\nArchitecture Style:Bungalow\nExterior Type:Back Yard, Front Yard, Garden/Play, Landscape Back, Landscape Front, Stream Seasona\nLiving Room:1\nBedroom:2\nBathroo:2\nParking:1\nProperty size:984 sqft\ncategory: Residential',
        img1:'/usa/12/1.webp',
        img2:'/usa/12/2.webp',
        img3:'/usa/12/3.webp',
        img4:'/usa/12/4.webp',
        img5:'/usa/12/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'9221 D St',
        pincode:'CA 94603',
        category: category.Residential,
        propertySize: '1078',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 549000,
        bedrooms: 3,
        bathrooms: 1,
        parking: 1,
        contactName: 'Perspective Real Estate',
        contactNumber: 'MLS#40984240',
        contactEmail: 'PerspectiveRealEstate@gmail.com',
        overview: 'Situated on an extra large lot and conveniently located for easy commuting, this is the property you’ve been looking for! This charming home comes with a detached garage that’s been converted to a bonus space equipped with french doors, a kitchenette and full bathroom. With a lot size of 6,250 square feet, the possibilities are endless!\n\nArchitecture Style:Ranch\nExterior Type:Exterior: Backyard, Back Yard, Front Yard, Side Yard, Storage, Low Maintenance\nLiving Room:1\nBedroom:3\nBathroo:1\nParking:1\nProperty size:1,078 sqft\ncategory:Residential',
        img1:'/usa/13/1.webp',
        img2:'/usa/13/2.webp',
        img3:'/usa/13/3.webp',
        img4:'/usa/13/4.webp',
        img5:'/usa/13/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'1866 Tiffin Rd',
        pincode:'CA 94602',
        category: category.Residential,
        propertySize: '1438',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1098000,
        bedrooms: 3,
        bathrooms: 3,
        parking: 2,
        contactName: 'Richmond',
        contactNumber: 'MLS#40984126',
        contactEmail: 'KarenRichmond@gmail.com',
        overview: 'Pristine 3BD/2BA mid-century offers style & sophistication! Built by OW Johnson in desirable Oakmore w/Rocky’s gourmet market & food truck Sundays in summer! Enjoy hillside views & nightly sunsets throughout the convenient H-shaped floor plan flooded w/natural light.\n\nArchitecture Style:Traditional,Mid Century Modern\nExterior Type:Backyard, Garden, Back Yard, Front Yard, Garden/Play, Side Yard, Sprinklers Automatic, Sprinklers Back, Sprinklers Front\nLiving Room:1\nBedroom:3\nBathroo:2\nParking:2\nProperty size:1,438 sqft\ncategory: Residential',
        img1:'/usa/14/1.webp',
        img2:'/usa/14/2.webp',
        img3:'/usa/14/3.webp',
        img4:'/usa/14/4.webp',
        img5:'/usa/14/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'35 Westminster Dr',
        pincode:'CA 94618',
        category: category.Residential,
        propertySize: '5000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 2295000,
        bedrooms: 4,
        bathrooms: 4,
        parking: 2,
        contactName: 'Anita Becker 01316805',
        contactNumber: 'MLS#40985004',
        contactEmail: 'AnitaBecker@gmail.com',
        overview: 'Welcome to this reimagined midcentury beauty in Claremont Pines! With beautiful interior and exterior upgrades, one can settle right in. Sweet courtyard accented with stunning crabapple tree leads to a level-in entry and reveals an open floorplan. Gorgeous living room with wood floors and fireplace flows effortlessly into the dining room.\n\nArchitecture Style:Mid Century Modern\nExterior Type:Back Yard\nLiving Room:1 Main\nBedroom:4\nBathroo:4\nParking:2\nProperty size:2,958 sqft\ncategory: Residential',
        img1:'/usa/15/1.webp',
        img2:'/usa/15/2.webp',
        img3:'/usa/15/3.webp',
        img4:'/usa/15/4.webp',
        img5:'/usa/15/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Georgia',
        location:'307 Warren St',
        pincode:'GA 30317',
        category: category.Residential,
        propertySize: '2600',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 725000,
        bedrooms: 4,
        bathrooms: 5,
        parking: 4,
        contactName: 'FMLS GA',
        contactNumber: '7017544',
        contactEmail: 'FMLSGA@gmail.com',
        overview: 'You don`t want to miss the sleek details of this beautiful Luxury new construction home! Walk into the inviting family room that opens to a breakfast room and Chef kitchen. The clean and sleek kitchen offers a 10ft waterfall Island with quartz counter-tops, a double pantry and stainless steel appliances. Family dinners can be enjoyed in the formal dining room.\n\nArchitecture Style:Contemporary/Modern\nExterior Type:Balcony, Private Entrance, Private Rear Entry, Private Yard, No Dock\nLiving Room:2\nBedroom:4\nBathroo:5\nParking:4\nProperty size:2,600 sqft\ncategory: Residential',
        img1:'/usa/16/1.webp',
        img2:'/usa/16/2.webp',
        img3:'/usa/16/3.webp',
        img4:'/usa/16/4.webp',
        img5:'/usa/16/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'McKinley II Plan in Camp Creek Village by Dan Ryan Builders',
        pincode:'60005',
        category: category.Residential,
        propertySize: '3846',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 502900,
        bedrooms: 5,
        bathrooms: 4,
        parking: 2,
        contactName: 'Dan Ryan Builders',
        contactNumber: '(770) 872-4148',
        contactEmail: 'DanRyanBuilders@gmail.com',
        overview: 'Attached 2 car garage.? Open concept kitchen with oversized granite island overlooking the breakfast area and family room with fireplace. ? First-floor guest suite with full bath. ? Dining room with coffered ceilings. ? Homeowner`s suite with sitting area, expansive walk-in closet, two separate vanities, soaking tub and oversized shower.\n\nArchitecture Style:Cholla\nExterior Type:Single Family Home\nLiving Room:1\nBedroom:5\nBathroo:4\nParking:2\nProperty size:3,846 sqft\ncategory: Residential',
        img1:'/usa/17/1.webp',
        img2:'/usa/17/2.webp',
        img3:'/usa/17/3.webp',
        img4:'/usa/17/4.webp',
        img5:'/usa/17/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Gorgeia',
        location:'585 Bismark Rd NE',
        pincode:'GA 30324',
        category: category.Residential,
        propertySize: '2707',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1125000,
        bedrooms: 4,
        bathrooms: 4,
        parking: 2,
        contactName: 'Scott Johnson',
        contactNumber: 'MLS#7017685',
        contactEmail: 'ScottJohnson@gmail.com',
        overview: 'Exquisite finishes will impress the most discerning eye throughout this expansive 4 bedroom, 3 and one-half bath rarely available single-family home in Manchester overlooking the community pool. Large black framed windows draw in an abundant amount of natural light throughout the home, from the owner`s suite to the main living area, and out to the spacious roof top deck with its own elevator serviced foyer and loggia.\n\nArchitecture Style:Contemporary/Modern\nExterior Type:Fenced, Front Yard\nLiving Room:1 main\nBedroom:4\nBathroo:4\nParking:2\nProperty size:2,707 sqft\ncategory: Residential',
        img1:'/usa/18/1.webp',
        img2:'/usa/18/2.webp',
        img3:'/usa/18/3.webp',
        img4:'/usa/18/4.webp',
        img5:'/usa/18/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Texas',
        location:'9125 Swanson Ln',
        pincode:'TX 78748',
        category: category.Residential,
        propertySize: '1090',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 415000,
        bedrooms: 2,
        bathrooms: 2,
        parking: 1,
        contactName: 'Rachel Mcdonald',
        contactNumber: 'MLS#8967763',
        contactEmail: 'RachelMcdonald@gmail.com',
        overview: 'OFFER DEADLINE MONDAY 10:00 AM! Charming Austin home featuring open floor plan, built in book shelves and kitchen is open to living room. Upgrades include, laminate & tile flooring installed in 2019/2020, new paint outside including brick in 2021, new paint in common areas inside 2021 & primary bath/closet 2022.\n\nArchitecture Style: Single Family Residence\nExterior Type: Private Yard\nLiving Room:1\nBedroom:2\nBathroo:2\nParking:1\nProperty size:1,090 sqft\ncategory:Residential',
        img1:'/usa/19/1.webp',
        img2:'/usa/19/2.webp',
        img3:'/usa/19/3.webp',
        img4:'/usa/19/4.webp',
        img5:'/usa/19/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Texas',
        location:'7407 Chisos Pass',
        pincode:'TX 78724',
        category: category.Residential,
        propertySize: '1475',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 524900,
        bedrooms: 3,
        bathrooms: 2,
        parking: 2,
        contactName: 'Darsh Parikh',
        contactNumber: 'MLS#3321580',
        contactEmail: 'DarshParikh@gmail.com',
        overview: 'A rare opportunity to purchase a one-of-a-kind stylish remodel with NO MONEY DOWN! This 3 bedroom + 2 bathroom east Austin beauty is immaculate and loaded with upgrades. This is an ideal first home or investment property as it is conveniently located near downtown, Mueller, Domain, Austin Airport, and several world-class restaurants.\n\nArchitecture Style:Single Family Residence\nExterior Type: Partial, Wood\nLiving Room:1\nBedroom:3\nBathroo:2\nParking:2\nProperty size:1,475 sqft\ncategory: Residential',
        img1:'/usa/20/1.webp',
        img2:'/usa/20/2.webp',
        img3:'/usa/20/3.webp',
        img4:'/usa/20/4.webp',
        img5:'/usa/20/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Texas',
        location:'12330 Havelock Dr',
        pincode:'TX 78759',
        category: category.Residential,
        propertySize: '5000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 645000,
        bedrooms: 3,
        bathrooms: 2,
        parking: 2,
        contactName: 'Abby Argo',
        contactNumber: 'MLS#1071493',
        contactEmail: 'AbbyArgo@gmail.com',
        overview: 'Beautifully remodeled single-story home in Walnut Crossing just minutes from upscale shopping and dining in The Domain. The open floor plan features custom cabinetry, quartz countertops, stainless-steel appliances, and an eat-in dining area with modern fixtures.n\nArchitecture Style:Single Family Residence\nExterior Type:Private Yard\nLiving Room:1\nBedroom:3\nBathroo:2\nParking:2\nProperty size:1,380 sqft\ncategory: Residential',
        img1:'/usa/21/1.webp',
        img2:'/usa/21/2.webp',
        img3:'/usa/21/3.webp',
        img4:'/usa/21/4.webp',
        img5:'/usa/21/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Massachusetts',
        location:'160 Elgin St',
        pincode:'MA 02459',
        category: category.Residential,
        propertySize: '5000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1338000,
        bedrooms: 3,
        bathrooms: 2,
        parking: 1,
        contactName: 'Ilene Solomon',
        contactNumber: 'MLS#72954258',
        contactEmail: 'IleneSolomon@gmail.com',
        overview: 'Enjoy all that nature has to offer from this quiet single-family home tucked away near the end of Elgin St. A quintessential “New England” street with mature trees which dead ends at the peaceful and serene Webster Woods. Schedule a showing to view this delightful well-cared for home next to nature today! Offers are due Tuesday at noon.\n\nArchitecture Style: Colonial\nExterior Type:Poured Concrete\nLiving Room:1\nBedroom:3\nBathroo:2\nParking:1\nProperty size:2,220 sqft\ncategory: Residential',
        img1:'/usa/22/1.webp',
        img2:'/usa/22/2.webp',
        img3:'/usa/22/3.webp',
        img4:'/usa/22/4.webp',
        img5:'/usa/22/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'3106 Unicornio St',
        pincode:'CA 92009',
        category: category.Residential,
        propertySize: '5000',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 1360000,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'Alyssa Guo DRE',
        contactNumber: '220005884',
        contactEmail: 'AlyssaGuoDRE#@gmail.com',
        overview: 'SWEEP OCEAN VIEWS FROM SOUTH CARSLBAD BEACHES UP TO THE PIER IN OCEANSIDE! Private and quiet big yard for family entertainment, the home fully Zen style, peaceful and relax. The neighborhood is highly sought after as each home is unique with NO HOA AND NO MELLO-ROOS.\n\nArchitecture Style:Detached\nExterior Type: Covered, Patio, Patio Open, Deck\nLiving Room:1\nBedroom:4\nBathroo:3\nParking:2\nProperty size:2,581 sqft\ncategory: Residential',
        img1:'/usa/23/1.webp',
        img2:'/usa/23/2.webp',
        img3:'/usa/23/3.webp',
        img4:'/usa/23/4.webp',
        img5:'/usa/23/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'California',
        location:'Arlington Heights',
        pincode:'CA 92009',
        category: category.Residential,
        propertySize: '1620',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 725000,
        bedrooms: 5,
        bathrooms: 5,
        parking: 3,
        contactName: 'Alisa Livesley',
        contactNumber: '(760) 419-1888',
        contactEmail: 'AlisaLivesley@gmail.com',
        overview: 'Incredible value and location! Your new Carlsbad home boasts infinite light from all new windows throughout. This two bedroom charmer features a spacious master suite, two balconies, light and bright kitchen plus dining room. Enter your home directly from the attached two car garage with lots of storage and laundry hookups!\n\nArchitecture Style:Condominium\nExterior Type:No Private Pool\nLiving Room:1\nBedroom:2\nBathroo:2\nParking:1\nProperty size:1,620 sqft\ncategory:Residential',
        img1:'/usa/24/1.webp',
        img2:'/usa/24/2.webp',
        img3:'/usa/24/3.webp',
        img4:'/usa/24/4.webp',
        img5:'/usa/24/5.webp',
    },{
        id:1,
        timeFrame:timeFrame.Monthly,
        subsciptionDate: '08/11/2022',
        currentlySubscribed: true,
        country:{name: 'United States of America', isoCode: 'US', flag: '🇺🇸', phonecode: '1', currency: 'USD'},
        state:'Massachusetts',
        location:'1011 Middlesex St #3',
        pincode:'MA 01851',
        category: category.Residential,
        propertySize: '1440',
        propertySizeType: propertySizeType.sqm,
        propertyType: propertyType.Villa,
        price: 309999,
        bedrooms: 2,
        bathrooms: 2,
        parking: 1,
        contactName: 'Christian Doherty',
        contactNumber: '72953723',
        contactEmail: 'ChristianDoherty@gmail.com',
        overview: 'This stunning townhome at the desirable Silva Estates. This 2 bedroom 1.5 bathroom unit with a one car garage is sure to impress! Lower level features an entryway with access to the garage and laundry room. The main level features a beautiful open concept layout with the kitchen that highlights an abundance of oak cabinets, granite countertops, matching appliances and access to the back deck.\n\nArchitecture Style:Townhouse,Condo\nExterior Type:Patio / Porch: Deck\nLiving Room:1\nBedroom:2\nBathroo:2\nParking:1\nProperty size:1,440 sqft\ncategory: Residential',
        img1:'/usa/25/1.webp',
        img2:'/usa/25/2.webp',
        img3:'/usa/25/3.webp',
        img4:'/usa/25/4.webp',
        img5:'/usa/25/5.webp',
    }]
}

const houseReducer = (state = initialState, action ) => {
    switch(action.type){
        case ADD_HOUSE: return {
                ...state,
                houses: [action.house,...state.houses]
            };
        default: return state;
    }
}

const searchReducer = (state = initialState, action) =>{
    switch(action.type){
        case SEARCH_HOUSE: 
        return{
            ...state,
            houses: state.houses
        }
        default: return state;
    }
}

export default houseReducer;